# -*- coding: utf-8 -*-
"""file_translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyjc3ty2W1gaWVCWsFzMJ_KjO56VW_Mp
"""

!pip install requests python-docx
from google.colab import userdata
userdata.get('SUBSCRIPTION_KEY')

import requests
import os
from docx import Document
location = "eastus2"
subscription_key = 'e203157f9b664da0bdece26d6c981207'
endpoint = 'https://api.cognitive.microsofttranslator.com/'

language_destination = 'pt-br'

def translator_text(text, target_language):
  path = '/translate'
  constructed_url = endpoint + path
  headers = {
      'Ocp-Apim-Subscription-Key': subscription_key,
      'Ocp-Apim-Subscription-Region': location,
      'Content-Type': 'application/json',
      'X-ClientTraceId': str(os.urandom(16))
  }

  body = [{
      'text': text
  }]
  params = {
      'api-version': '3.0',
      'from': 'en',
      'to': target_language
  }

  request = requests.post(constructed_url, params=params, headers=headers, json=body)
  response = request.json()
  return response[0]["translations"][0]["text"]

translator_text("I know you're somewhere out here, somewhere far away, waiting for me", language_destination)

def translate_document(path):
  document = Document(path)
  full_text = []
  for paragraph in document.paragraphs:
    translated_text = translator_text(paragraph.text, language_destination)
    full_text.append(translated_text)

    translated_doc = Document()
    for line in full_text:
      print(line)
      translated_doc.add_paragraph(line)
    path_translated = path.replace(".docx", f"_{language_destination}.docx")
    translated_doc.save(path_translated)
    return path_translated

input_file = "/content/musica.docx"
translate_document(input_file)